name = "Newb Lunarwake"
version = [1, 0, 0]
min_supported_mc_version = [1, 26, 30]
description = '''
§c%w
§7- A vanilla-styled Bedrock shader 
%v
''' # %w = patch warning, %v = version
authors = ["krispyBRN", "devendrn"]
url = "https://github.com/krispyBRN/newb-lunarwake"
uuid = "3b499b88-7872-4db5-b18e-f52b7d96fb93"
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "ActorMultiTexture", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2026 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''Lynx, Rexytmc
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
